version: '3.8'

services:
  backend:
    image: node:20
    working_dir: /app
    command: /bin/sh -c "npm run dev"
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/crm-app
      - JWT_SECRET=your-secret-key-here
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  frontend:
    image: node:20
    working_dir: /app
    command: /bin/sh -c "npm run start"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
